#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
COUNTER=1
while [ "$COUNTER" -le 10 ]; do
	if [ "$COUNTER" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((COUNTER++))
done
