#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School for the other iteration
COUNTER=1
while [ "$COUNTER" -le 10 ]; do
	if [ "$COUNTER" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$COUNTER" -eq 8 ]
	then 
		echo "good luck"
	else 
		echo "Best School"
	fi
	((COUNTER++))
done
